# Makefile for building testcrc32
# Generated by tmake at 18:10, 2010/11/27
#     Project: main.pro
#    Template: app
#############################################################################

####### Compiler, tools and options

CC	=	gcc
CXX	=	g++
CFLAGS	=	-g -pipe -Wall -W -O2 
CXXFLAGS=	-g -pipe -Wall -W -O2 
INCPATH	=	
LINK	=	g++
LFLAGS	=	
LIBS	=	$(SUBLIBS)  
MOC	=	$(QTDIR)/bin/moc
UIC	=	$(QTDIR)/bin/uic
REMOVE	=	rm -f
TAR	=	tar -cf
GZIP	=	gzip -9f

####### Files

HEADERS =	
SOURCES =	main.cpp
OBJECTS =	main.o
INTERFACES =	
UICDECLS =	
UICIMPLS =	
SRCMOC	=	
OBJMOC	=	
DIST	=	
TARGET	=	testcrc32
INTERFACE_DECL_PATH = .

####### Implicit rules

.SUFFIXES: .cpp .cxx .cc .C .c

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $@ $<

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $@ $<

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $@ $<

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $@ $<

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o $@ $<

####### Build rules


all: $(TARGET)

$(TARGET): $(UICDECLS) $(OBJECTS) $(OBJMOC) 
	$(REMOVE) $(TARGET) 
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJMOC) $(LIBS)

moc: $(SRCMOC)

tmake: Makefile

Makefile: main.pro
	tmake main.pro -o Makefile

dist:
	$(REMOVE) Makefile *.kdevprj *.kdevses core* *~

clean:
	$(REMOVE) $(OBJECTS) $(OBJMOC) $(SRCMOC) $(UICIMPLS) $(UICDECLS) $(TARGET)


####### Compile

main.o: main.cpp

